version: 1 
# schema
tables: 
  - name: raw_customers
    type: csv 
    path: ./testing/test1/raw_customers.csv
  - name: customer_infos
    type: csv 
    path: ./testing/test1/customer_infos.csv
models:
  - name: Customer
    table: raw_customers
    columns: 
    - name: id
      type: string 
      primary: true
    - name: first_name 
      type: string 
    - name: last_name 
      type: string 
  - name: Company
    table: raw_customers
    columns:
    - name: company
      type: string 
      primary: true 
  - name: CustomerInfo
    table: customer_infos
    columns:
    - name: id
      type: string       
      primary: true
    - name: age
      type: integer
    - name: state
      type: string

