version: 1 

sources: 
  - name: raw_customers
    type: csv 
    path: ./testing/test1/raw_customers.csv
models:
  - name: Customer
    source: raw_customers
    columns: 
    - name: id
      type: string 
    - name: first_name 
      type: string 
    - name: last_name 
      type: string 
  - name: Company
    source: raw_customers
    columns:
    - name: company
      type: string 
     

    
