version: 1 

tables: 
  - name: raw_customers
    type: csv 
    path: ./testing/test1/raw_customers.csv
  - name: customer_infos
    type: csv 
    path: ./testing/test1/customer_infos.csv
models:
  - name: Customer
    table: raw_customers
    columns: 
    - name: id
      type: string 
    - name: first_name 
      type: string 
    - name: last_name 
      type: string 
  - name: Company
    table: raw_customers
    columns:
    - name: company
      type: string 
  - name: CustomerInfo
    table: customer_infos
    columns:
    - name: id
      type: string       
    - name: age
      type: integer
    - name: state
      type: string
links: 
  - a: Customer.id 
    b: CustomerInfo.id
    
     

    
