# all constants used in this project
FILTERS = 'filters'
NAME = 'name'
TYPE = 'type'
ENTITY = 'entity'
ENTITY_TYPES = 'entity_types'
TABLE = 'table'
MODELS= 'models'
TABLES = 'tables'
TABLE = 'table'
SOURCE= 'source'
COLUMNS='columns'
FIELD = 'field'
PATH = 'path'
ALIASES = 'aliases'
SELECTS = 'selects'

LINKS = 'links'
A = 'a'
B = 'b'
