# all constants used in this project
OP = 'op'
FILTERS = 'filters'
NAME = 'name'
TYPE = 'type'
ENTITY = 'entity'
ENTITY_TYPES = 'entity_types'
TABLE = 'table'
MODELS= 'models'
TABLES = 'tables'
TABLE_NAME = 'table_name'
TABLE = 'table'
SOURCE= 'source'
COLUMN = 'column'
COLUMNS='columns'
FIELD = 'field'
PATH = 'path'
ALIASES = 'aliases'
SELECTS = 'selects'

AND = 'and'
OR = 'or'
